on:
  workflow_dispatch:

name: BUILD | backend container

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Check for dockerenv file
      #  run: pwd ; ls -alih ; env
      - name: Set env vars
        run: |
          echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV

          echo 'tf_auto_ws<<EOF' >> $GITHUB_ENV
          cat tf_ws.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          env
      - name: Check after for dockerenv file
        env:
          MY_ENV_VAR: ${{ (github.event_name == 'schedule' || contains(fromJson(fromJson(env.tf_auto_ws)), "terraform/ws1") ) && 'auto' || 'manual' }}
        run: echo $MY_ENV_VAR
          # 


            
