on:
  workflow_dispatch:

name: BUILD | backend container

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      all_secrets: ${{ toJson(secrets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for dockerenv file
        run: pwd ; ls -alih ; env
      - name: Load all secrets to env
        run: |
          echo "$all_secrets" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
      - name: Check after for dockerenv file
        run: pwd ; ls -alih ; env
