on:
  workflow_dispatch:

name: BUILD | backend container

jobs:
  docker-publish:
    name: docker-publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        REPO_FQDN: ${{ github.ref_name }}
      run: |
        echo $REPO_FQDN
