on:
  workflow_dispatch:

name: BUILD | backend container

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Check for dockerenv file
      #  run: pwd ; ls -alih ; env
      - name: Set env vars
        run: |
          echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
          #cat .env.local >> $GITHUB_ENV
          source .env.local
          env
      - name: Check after for dockerenv file
        run: pwd ; ls -alih ; env; echo $FFFFF
