on:
  workflow_dispatch:

name: BUILD | backend container

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: ls -alih
